# Generated by Django 4.2.9 on 2024-02-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_pedido_id_alter_producto_id_alter_proveedor_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Personal',
        ),
    ]
