# Generated by Django 4.2.9 on 2024-02-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_proveedor_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
